### PR TITLE
update dependencies to latest

### PR DESCRIPTION
**Pull request by thjaeckle**
* mongo java driver
* netty
* log4j
* scala to latest patch releases

### CODE REVIEW

**Comment by thjaeckle** [comment]
@scullxbones I would propose to update dependencies to latest and then afterwards do a release - including the Scala 3 artifacts from PR #15 

Is that ok for you? Would you choose version `1.1.0` or `1.0.3`?

**Comment by scullxbones** [comment]
@thjaeckle sounds great!  Should I set up Scala steward on this repo?  That would at least automate dependency management.

I think a minor is appropriate in general so `1.1.0`

**Comment by thjaeckle** [comment]
> Should I set up Scala steward on this repo? That would at least automate dependency management.

@scullxbones cannot hurt, I would say

**Comment by scullxbones** [comment]
FYI https://github.com/VirtusLab/scala-steward-repos/pull/351

**Pull request merged**
