### PR TITLE
make metadata index name configurable

### PR DESCRIPTION
**Pull request by alstanchev**
This PR makes the metadata collection index name configurable.

I have changed the default value  from "pekko_persistence_metadata_pid" to "pekko_persistence_metadata_index"
for consistency with other configs.
And also in the case of migration it should be configured anyways or in the case of a fresh db it would not matter.

Resolves: #10

### CODE REVIEW

**Review by thjaeckle — CHANGES_REQUESTED** [review]
Thanks a lot for the contribution @alstanchev 

I missed that one when documenting the migration from akka-persistence-mongo to pekko-persistence-mongo in #11 

And it turns out that without this fix (making the index configurable), #10 would still happen.

Just one thing:  
Could you please adjust the `README.md` to
* [document the index name in the index settings](https://github.com/scullxbones/pekko-persistence-mongo#mongo-collection-index-settings)
* [document the index rename in the migration notes](https://github.com/scullxbones/pekko-persistence-mongo#migrating-from-akka-persistence-mongo-to-pekko-persistence-mongo)

**Review by thjaeckle — APPROVED** [review]
Looks good to me.

Thanks a lot for the contribution.

**Comment by scullxbones** [comment]
@thjaeckle - I was able to confirm that GH actions can publish now.  All that's needed is pushing a tag, e.g.

```shell
> git tag -a v1.0.1 -m '1.0.1 Release' -s
> git push --tags
```

**Comment by thjaeckle** [comment]
@scullxbones awesome, thanks .. I will try it

**Pull request merged**
