### PR TITLE
Cross-building to Scala 3

### PR DESCRIPTION
**Pull request by SakulK**
Fixes https://github.com/scullxbones/pekko-persistence-mongo/issues/13
`mongo-scala-driver` doesn't have a scala 3 version, but `CrossVersion.for3Use2_13` seems to work well enough in this case

### CODE REVIEW

**Review by thjaeckle — APPROVED** [review]
Looks good to me.
@scullxbones do you also want to have a look?

**Comment by pjfanning** [comment]
Could we document this -  because CrossVersion.for3Use2_13 is discouraged for libs:

https://github.com/akka/akka/issues/31200

**Comment by SakulK** [comment]
I added a warning in the README, but of course if you decide this is a blocker for merging the PR - I understand

**Comment by scullxbones** [comment]
Yep this looks fine to me.  👍 

Is there a ticket on the mongodb side tracking a Scala 3 upgrade for the driver?

**Comment by thjaeckle** [comment]
There are tickets in Mongo's Jira about Scala3:
* https://jira.mongodb.org/browse/JAVA-5261
* https://jira.mongodb.org/browse/JAVA-4181

**Comment by pjfanning** [comment]
https://jira.mongodb.org/plugins/servlet/mobile#issue/JAVA-4181

The bson driver code uses Scala2 macros. So, it may be a while before someone submits a version that works with Scala3.

**Pull request merged**
